version: '3'
services:
  neo4j:
    image: neo4j:5
    container_name: graphql-test-neo4j
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./db_volume/conf:/conf
      - ./db_volume/data:/data
      - ./db_volume/import:/import
      - ./db_volume/logs:/logs
    environment: 
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_AUTH=neo4j/terriblyinsecure

  graphql-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: graphql-api
    restart: unless-stopped
    ports:
      - '8000:8000'
    depends_on:
      - neo4j
